services:
  ioweyou:
    image: ioweyou
    build:
      context: .
      dockerfile: IOweYou/Dockerfile
    ports:
      - "5000:80"
    environment:
      - QR-CODE-API-KEY=yourqrcodekey
      - HOST=yourhostname
      - PORT=yourport
      - USERNAME=yourusername
      - PASSWORD=yourpassword
      - FROMMAILADDRESS=yourmailaddress
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ioweyou
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
