services:
  ioweyou:
    image: ioweyou
    build:
      context: .
      dockerfile: IOweYou/Dockerfile
    ports:
      - "5000:80"
    environment:
      - QR-CODE-API-KEY=yourqrcodekey
      - HOST=yourhostname
      - PORT=yourport
      - USERNAME=yourusername
      - PASSWORD=yourpassword
      - FROMMAILADDRESS=yourmailaddress
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ioweyou-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ioweyou
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - ioweyou-network

networks:
  ioweyou-network:
    driver: bridge

volumes:
  mysql_data: